import ProjectDescription
import ProjectDescriptionHelpers

// https://docs.tuist.io/manifests/workspace
let workspace = Workspace(
    name: "NutritionalPlanWorkspace",
    projects: [
        // Apps
        .relativeToApps("**"),
        // Modules
        .relativeToModules("**")
    ],
    schemes: [
        .nutritionalPlanScheme
    ],
    additionalFiles: [
        "README.md"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        renderMarkdownReadme: true
    )
)
